[versions]
agp = "8.13.0"
activityCompose = "1.11.0"
androidx-lifecycle = "2.9.4"
composeBom = "2025.09.00"
composeMultiplatform = "1.9.0"
coreKtx = "1.17.0"
datastorePreferences = "1.1.7"
junit = "4.13.2"
composeHotReload = "1.0.0-beta08"
kotlin = "2.2.20"
kotlinStdlib = "2.2.20"
kotlinxDatetime = "0.7.1"
kotlinxSerializationJson = "1.9.0"
ktor = "3.3.0"
ktorClientContentNegotiation = "3.3.0"
lifecycleRuntimeKtx = "2.9.4"
materialIconsCore = "1.7.3"
navigationCompose = "2.9.0"
runtimeLivedata = "1.9.1"
multiplatformSettings = "1.3.0"

[libraries]
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "materialIconsCore" }
multiplatform-settings-no-arg = { group = "com.russhwolf", name = "multiplatform-settings-no-arg", version.ref = "multiplatformSettings" }
multiplatform-settings = { group = "com.russhwolf", name = "multiplatform-settings", version.ref = "multiplatformSettings" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material3-window-size-class1 = { module = "androidx.compose.material3:material3-window-size-class" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedata" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-material3-window-size-class1 = { module = "androidx.compose.material3:material3-window-size-class" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinStdlib" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktorClientContentNegotiation" }
ktor-bom = { group = "io.ktor", name = "ktor-bom", version.ref = "ktor" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core"}
ktor-client-json = { group = "io.ktor", name = "ktor-client-json" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging" }
ktor-client-serialization = { group = "io.ktor", name = "ktor-client-serialization" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation" }
ktor-client-auth = { group = "io.ktor", name = "ktor-client-auth"}
ktor-client-encoding = { group = "io.ktor", name = "ktor-client-encoding"}
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin" }
ktor-client-js = { group = "io.ktor", name = "ktor-client-js" }
ktor-client-java = { group = "io.ktor", name = "ktor-client-java" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp"}

[bundles]
ktor-common = ["ktor-client-core", "ktor-client-json", "ktor-client-logging",
    "ktor-client-serialization", "ktor-client-content-negotiation",
    "ktor-serialization-kotlinx-json", "ktor-client-auth", "ktor-client-encoding"]


[plugins]
androidLibrary = {id = "com.android.library", version.ref = "agp" }
androidApplication = {id = "com.android.application", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
